[package]
name = "window_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "0.20"
winit = "0.30.12"
env_logger = "0.11"
log = "0.4"
bytemuck = { version = "1.16", features = ["derive"] }
pollster = "0.3"
cgmath = "0.18"
image = "0.25"
gltf = "1.4"